Eval:
  Enabled: false

LineLength:
  Enabled: false

# Configuration parameters: AllowedVariables.
GlobalVars:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
MethodName:
  Enabled: false

OpMethod:
  Enabled: false

Void:
  Enabled: false

SpaceInsideParens:
  Enabled: false

SpaceAroundOperators:
  Enabled: false
